version: '3'
services:
    restaurantDB:
        container_name: restaurantDB
        platform: linux/amd64 #for platform error on Apple M1 chips
        restart: unless-stopped
        env_file: .env
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_HOST: '%'
        volumes:
            - .tmp/data:/var/lib/mysql
            #- ./data:/var/lib/mysql # if you want to use a bind folder
        ports:
            - '${DB_PORT}:3306'
        networks:
            - app

volumes:
    app-data:

networks:
    app:
        name: Restaurant
        driver: bridge
