version: '3'
services:
    app:
        container_name: restaurantApp
        restart: always
        env_file: .env
        image: 'dtluat259/restaurant-app:main'
        ports:
            - '3000:${PORT}'
        networks:
            - app

volumes:
    app-data:

networks:
    app:
        name: Restaurant
        driver: bridge
