version: '3'
services:
    mysql:
        platform: linux/amd64
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1 --sql_mode=""
        container_name: tien-local-mysql
        restart: always
        env_file: .env
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: luat
            MYSQL_USER: luat
            MYSQL_PASSWORD: luat
        volumes:
            - ./.data:/var/lib/mysql
