import { FloorRestaurant } from './../../src/modules/table-diagram/tableDiagram.constant';
import { MigrationInterface, QueryRunner } from 'typeorm';
import { TABLE_NAME } from '../constant';

export class SeedingTablesRestaurant1720963593404
    implements MigrationInterface
{
    public async up(queryRunner: QueryRunner): Promise<void> {
        const tables = [
            {
                name: '1-1',
                status: 'booked',
                numberSeat: 1,
                arrivalTime: '2022-04-20 17:00:00',
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-2',
                status: 'booked',
                numberSeat: 2,
                arrivalTime: '2022-04-20 17:00:00',
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-3',
                status: 'ready',
                numberSeat: 4,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-4',
                status: 'ready',
                numberSeat: 10,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-5',
                status: 'used',
                numberSeat: 6,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-6',
                status: 'ready',
                numberSeat: 2,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-7',
                status: 'ready',
                numberSeat: 8,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-8',
                status: 'used',
                numberSeat: 10,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-9',
                status: 'ready',
                numberSeat: 4,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-10',
                status: 'ready',
                numberSeat: 2,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-11',
                status: 'ready',
                numberSeat: 4,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-12',
                status: 'ready',
                numberSeat: 10,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-13',
                status: 'ready',
                numberSeat: 6,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-14',
                status: 'ready',
                numberSeat: 2,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-15',
                status: 'ready',
                numberSeat: 4,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-16',
                status: 'ready',
                numberSeat: 8,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-17',
                status: 'ready',
                numberSeat: 8,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '1-18',
                status: 'ready',
                numberSeat: 8,
                floor: FloorRestaurant.FIRST,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-1',
                status: 'booked',
                numberSeat: 1,
                arrivalTime: '2022-04-20 17:00:00',
                floor: FloorRestaurant.SECOND,

                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-2',
                status: 'booked',
                numberSeat: 2,
                arrivalTime: '2022-04-20 17:00:00',
                floor: FloorRestaurant.SECOND,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-3',
                status: 'ready',
                numberSeat: 4,
                floor: FloorRestaurant.SECOND,

                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-4',
                status: 'ready',
                numberSeat: 10,
                floor: FloorRestaurant.SECOND,

                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-5',
                status: 'used',
                numberSeat: 6,
                floor: FloorRestaurant.SECOND,

                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-6',
                status: 'ready',
                numberSeat: 2,
                floor: FloorRestaurant.SECOND,

                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-7',
                status: 'ready',
                numberSeat: 8,
                floor: FloorRestaurant.SECOND,

                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-8',
                status: 'used',
                numberSeat: 10,
                floor: FloorRestaurant.SECOND,

                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-9',
                status: 'ready',
                numberSeat: 4,
                floor: FloorRestaurant.SECOND,

                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-10',
                status: 'ready',
                numberSeat: 2,
                floor: FloorRestaurant.SECOND,

                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-11',
                status: 'ready',
                numberSeat: 4,
                floor: FloorRestaurant.SECOND,

                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '2-12',
                status: 'ready',
                numberSeat: 10,
                floor: FloorRestaurant.SECOND,

                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-1',
                status: 'booked',
                numberSeat: 1,
                arrivalTime: '2022-04-20 17:00:00',
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-2',
                status: 'booked',
                numberSeat: 2,
                arrivalTime: '2022-04-20 17:00:00',
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-3',
                status: 'ready',
                numberSeat: 4,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-4',
                status: 'ready',
                numberSeat: 10,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-5',
                status: 'used',
                numberSeat: 6,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-6',
                status: 'ready',
                numberSeat: 2,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-7',
                status: 'ready',
                numberSeat: 8,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-8',
                status: 'used',
                numberSeat: 10,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-9',
                status: 'ready',
                numberSeat: 4,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-10',
                status: 'ready',
                numberSeat: 2,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-11',
                status: 'ready',
                numberSeat: 4,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-12',
                status: 'ready',
                numberSeat: 10,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-13',
                status: 'ready',
                numberSeat: 6,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-14',
                status: 'ready',
                numberSeat: 2,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-15',
                status: 'ready',
                numberSeat: 4,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-16',
                status: 'ready',
                numberSeat: 8,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
            {
                name: '3-17',
                status: 'ready',
                numberSeat: 8,
                floor: FloorRestaurant.THIRD,
                createdAt: new Date(),
                updatedAt: new Date(),
                createdBy: 1,
                updatedBy: 1,
            },
        ];
        await queryRunner.manager
            .getRepository(TABLE_NAME.TablesRestaurants)
            .insert(tables);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.manager
            .getRepository(TABLE_NAME.TablesRestaurants)
            .delete({});
    }
}
